name: my_profile_counter_app
description: A Flutter application for profile and counter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo Polinema.png
    - assets/gambar/Logo Polinema.png
    - assets/images/profile.jpg
